export interface EventData {
  id: string;
  name: string;
  date: string;
  endDate: string;
  location: string;
  theme: string;
  status: string;
  statusLabel: string;
  participants: number;
  maxParticipants?: number;
  budget: number;
  spent: number;
  csat: number;
  progress: number;
  description: string;
  organizer: string;
  checklistDone: number;
  checklistTotal: number;
  preTestAvg: number;
  postTestAvg: number;
  published: boolean;
  shortDescription: string;
  coverGradient: string;
  highlights: string[];
  // Pricing
  price: number;
  earlyBirdPrice?: number;
  earlyBirdDeadline?: string;
  paymentMethods?: string[];
  // Event Type
  eventType: "public" | "internal";
}

export const eventsDB: Record<string, EventData> = {
  EVT001: {
    id: "EVT001",
    name: "Workshop Public Speaking 2024",
    date: "15 Sep 2024",
    endDate: "16 Sep 2024",
    location: "Hotel X, Jakarta",
    theme: "Speak with Confidence",
    status: "completed",
    statusLabel: "Selesai",
    participants: 47,
    maxParticipants: 50,
    budget: 40000000,
    spent: 17000000,
    csat: 4.6,
    progress: 100,
    description: "Workshop intensif public speaking selama 2 hari dengan 47 peserta dari berbagai perusahaan dan instansi. Mencakup teknik dasar hingga advanced public speaking dengan praktik langsung.",
    organizer: "Sarah - Event Manager",
    checklistDone: 17,
    checklistTotal: 17,
    preTestAvg: 62,
    postTestAvg: 81,
    published: true,
    shortDescription: "Workshop intensif 2 hari tentang teknik public speaking dengan 47 peserta dari berbagai perusahaan.",
    coverGradient: "from-orange-400 to-orange-600",
    highlights: ["47 Peserta", "CSAT 4.6", "Peningkatan +19 poin"],
    price: 1500000,
    earlyBirdPrice: 1200000,
    earlyBirdDeadline: "31 Aug 2024",
    paymentMethods: ["Transfer Bank", "OVO", "GoPay", "Dana"],
    eventType: "public",
  },
  EVT002: {
    id: "EVT002",
    name: "Kelas Coaching Batch 5",
    date: "1 Okt 2024",
    endDate: "5 Okt 2024",
    location: "Sanrays Office",
    theme: "Leadership Mastery",
    status: "active",
    statusLabel: "Berlangsung",
    participants: 32,
    maxParticipants: 40,
    budget: 25000000,
    spent: 12000000,
    csat: 4.3,
    progress: 65,
    description: "Program coaching leadership selama 5 hari untuk team leaders dan middle management. Fokus pada pengembangan kemampuan memimpin dan mengelola tim.",
    organizer: "Sarah - Event Manager",
    checklistDone: 10,
    checklistTotal: 16,
    preTestAvg: 58,
    postTestAvg: 75,
    published: true,
    shortDescription: "Program coaching leadership 5 hari untuk team leaders dan middle management.",
    coverGradient: "from-blue-400 to-blue-600",
    highlights: ["32 Peserta", "5 Hari", "Leadership Focus"],
    price: 3500000,
    earlyBirdPrice: 2800000,
    earlyBirdDeadline: "15 Sep 2024",
    paymentMethods: ["Transfer Bank", "Kartu Kredit", "Cicilan 0%"],
    eventType: "public",
  },
  EVT004: {
    id: "EVT004",
    name: "Seminar Digital Marketing 2024",
    date: "20 Okt 2024",
    endDate: "20 Okt 2024",
    location: "Hotel Indonesia, Jakarta",
    theme: "Digital Marketing Revolution",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 150,
    budget: 75000000,
    spent: 15000000,
    csat: 0,
    progress: 25,
    description: "Seminar satu hari tentang strategi digital marketing terbaru termasuk SEO, social media marketing, dan content strategy untuk bisnis modern.",
    organizer: "Andi - Marketing Director",
    checklistDone: 4,
    checklistTotal: 18,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Seminar digital marketing dengan praktisi berpengalaman dari perusahaan tech besar.",
    coverGradient: "from-purple-400 to-pink-500",
    highlights: ["150 Kuota", "5 Pemateri", "Sertifikat"],
    price: 500000,
    earlyBirdPrice: 350000,
    earlyBirdDeadline: "1 Okt 2024",
    paymentMethods: ["Transfer Bank", "OVO", "GoPay", "Dana", "QRIS"],
    eventType: "public",
  },
  EVT005: {
    id: "EVT005",
    name: "Workshop Time Management",
    date: "5 Nov 2024",
    endDate: "5 Nov 2024",
    location: "Gedung Serbaguna, Bandung",
    theme: "Manage Your Time, Manage Your Life",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 60,
    budget: 20000000,
    spent: 0,
    csat: 0,
    progress: 10,
    description: "Workshop intensif 1 hari tentang teknik manage waktu efektif untuk meningkatkan produktivitas kerja dan kehidupan sehari-hari.",
    organizer: "Rina - Training Manager",
    checklistDone: 2,
    checklistTotal: 14,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Pelajari teknik time management dari praktisi yang sudah terbukti hasilnya.",
    coverGradient: "from-cyan-400 to-blue-500",
    highlights: ["1 Hari", "60 Kuota", "Template Gratis"],
    price: 750000,
    earlyBirdPrice: 600000,
    earlyBirdDeadline: "20 Okt 2024",
    paymentMethods: ["Transfer Bank", "OVO", "GoPay"],
    eventType: "public",
  },
  EVT006: {
    id: "EVT006",
    name: "Masterclass Financial Planning",
    date: "12 Nov 2024",
    endDate: "14 Nov 2024",
    location: "Ayana Hotel, Jakarta",
    theme: "Build Your Wealth",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 35,
    budget: 60000000,
    spent: 5000000,
    csat: 0,
    progress: 15,
    description: "Masterclass 3 hari tentang perencanaan keuangan personal dan investasi. Cocok untuk profesional yang ingin mengoptimalkan keuangan mereka.",
    organizer: "Budi - Finance Director",
    checklistDone: 3,
    checklistTotal: 20,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Masterclass 3 hari tentang investasi, pajak, dan perencanaan keuangan.",
    coverGradient: "from-emerald-400 to-teal-500",
    highlights: ["3 Hari", "35 Peserta", "Konsultasi 1-on-1"],
    price: 7500000,
    earlyBirdPrice: 6000000,
    earlyBirdDeadline: "25 Okt 2024",
    paymentMethods: ["Transfer Bank", "Kartu Kredit", "Cicilan 0%"],
    eventType: "public",
  },
  EVT007: {
    id: "EVT007",
    name: "Kelas Public Speaking untuk Profesional",
    date: "25 Nov 2024",
    endDate: "26 Nov 2024",
    location: "Ballroom Hotel Mulia, Jakarta",
    theme: "Speak Like a Pro",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 45,
    budget: 45000000,
    spent: 0,
    csat: 0,
    progress: 5,
    description: "Kelas intensif public speaking untuk profesional yang ingin meningkatkan kemampuan presentasi dan komunikasi di tempat kerja.",
    organizer: "Sarah - Event Manager",
    checklistDone: 1,
    checklistTotal: 16,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Kelas 2 hari teknik presentasi dan public speaking level profesional.",
    coverGradient: "from-amber-400 to-orange-500",
    highlights: ["45 Peserta", "2 Hari", "Video Recording"],
    price: 2500000,
    earlyBirdPrice: 2000000,
    earlyBirdDeadline: "1 Nov 2024",
    paymentMethods: ["Transfer Bank", "OVO", "GoPay", "Kartu Kredit"],
    eventType: "public",
  },
  EVT003: {
    id: "EVT003",
    name: "Team Building Q4 2024",
    date: "15 Nov 2024",
    endDate: "17 Nov 2024",
    location: "Villa Bintang, Puncak",
    theme: "Build Stronger Team",
    status: "preparation",
    statusLabel: "Persiapan",
    participants: 25,
    maxParticipants: 30,
    budget: 35000000,
    spent: 5000000,
    csat: 0,
    progress: 40,
    description: "Team building 3 hari 2 malam di villa untuk mempererat kebersamaan tim melalui berbagai aktivitas outdoor dan indoor.",
    organizer: "Sarah - Event Manager",
    checklistDone: 6,
    checklistTotal: 15,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Team building 3 hari 2 malam di villa Puncak untuk mempererat kebersamaan tim.",
    coverGradient: "from-emerald-400 to-emerald-600",
    highlights: ["25 Peserta", "3 Hari 2 Malam", "Outdoor Activities"],
    price: 0,
    eventType: "internal",
  },
  EVT008: {
    id: "EVT008",
    name: "Leadership Camp Q1 2025",
    date: "10 Jan 2025",
    endDate: "12 Jan 2025",
    location: "Camp Ground, Bogor",
    theme: "Leading Through Challenges",
    status: "preparation",
    statusLabel: "Persiapan",
    participants: 0,
    maxParticipants: 25,
    budget: 40000000,
    spent: 0,
    csat: 0,
    progress: 5,
    description: "Leadership camp 3 hari 2 malam untuk para manager dan team leader. Fokus pada pengembangan kepemimpinan di bawah tekanan.",
    organizer: "HR Department",
    checklistDone: 1,
    checklistTotal: 18,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Leadership camp intensif untuk mengembangkan kemampuan memimpin di situasi sulit.",
    coverGradient: "from-indigo-400 to-purple-600",
    highlights: ["25 Peserta", "3 Hari 2 Malam", "Survival Skills"],
    price: 0,
    eventType: "internal",
  },
  EVT009: {
    id: "EVT009",
    name: "Annual Town Hall Meeting",
    date: "15 Des 2024",
    endDate: "15 Des 2024",
    location: "Head Office, Jakarta",
    theme: "Year in Review 2024",
    status: "preparation",
    statusLabel: "Persiapan",
    participants: 150,
    maxParticipants: 200,
    budget: 100000000,
    spent: 25000000,
    csat: 0,
    progress: 30,
    description: "Town hall meeting tahunan untuk seluruh karyawan. Penyampaian年度报告, penghargaan karyawan berprestasi, dan freezing day.",
    organizer: "CEO Office",
    checklistDone: 6,
    checklistTotal: 22,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Town hall meeting tahunan untuk seluruh karyawan dan manajemen.",
    coverGradient: "from-rose-400 to-pink-500",
    highlights: ["200 Peserta", "Awards Night", "Gala Dinner"],
    price: 0,
    eventType: "internal",
  },
  EVT010: {
    id: "EVT010",
    name: "Skills Workshop: Excel Advanced",
    date: "8 Nov 2024",
    endDate: "8 Nov 2024",
    location: "Training Room Lantai 5",
    theme: "Master Excel for Business",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 30,
    budget: 5000000,
    spent: 0,
    csat: 0,
    progress: 10,
    description: "Workshop excel tingkat lanjut untuk staff dan junior manager. Meng-cover pivot table, macro, dan data analysis.",
    organizer: "IT Department",
    checklistDone: 1,
    checklistTotal: 12,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Workshop Excel tingkat lanjut untuk meningkatkan produktivitas kerja.",
    coverGradient: "from-green-400 to-emerald-500",
    highlights: ["30 Peserta", "1 Hari", "Sertifikat"],
    price: 0,
    eventType: "internal",
  },
  EVT011: {
    id: "EVT011",
    name: "Customer Service Excellence Training",
    date: "20 Nov 2024",
    endDate: "21 Nov 2024",
    location: "Hotel Aston, Bandung",
    theme: "Delivering Wow Experience",
    status: "preparation",
    statusLabel: "Akan Datang",
    participants: 0,
    maxParticipants: 40,
    budget: 35000000,
    spent: 0,
    csat: 0,
    progress: 8,
    description: "Training 2 hari untuk tim customer service tentang cara memberikan pengalaman pelanggan yang excepcional.",
    organizer: "Customer Success Team",
    checklistDone: 2,
    checklistTotal: 16,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Training customer service untuk tim yang berhadapan langsung dengan klien.",
    coverGradient: "from-sky-400 to-cyan-500",
    highlights: ["40 Peserta", "2 Hari", "Role Play"],
    price: 0,
    eventType: "internal",
  },
  EVT012: {
    id: "EVT012",
    name: "New Employee Onboarding Program",
    date: "1 Nov 2024",
    endDate: "3 Nov 2024",
    location: "Office HQ",
    theme: "Welcome to the Family",
    status: "active",
    statusLabel: "Berlangsung",
    participants: 15,
    maxParticipants: 20,
    budget: 20000000,
    spent: 12000000,
    csat: 4.7,
    progress: 60,
    description: "Program orientasi untuk karyawan baru. Memperkenalkan budaya perusahaan, sistem, dan tim.",
    organizer: "HR Department",
    checklistDone: 10,
    checklistTotal: 16,
    preTestAvg: 0,
    postTestAvg: 0,
    published: true,
    shortDescription: "Program orientasi karyawan baru selama 3 hari.",
    coverGradient: "from-violet-400 to-purple-500",
    highlights: ["15 Peserta", "3 Hari", "Buddy System"],
    price: 0,
    eventType: "internal",
  },
};

export function getPublishedEvents(): EventData[] {
  return Object.values(eventsDB).filter((e) => e.published);
}

export function getEvent(id: string): EventData | undefined {
  return eventsDB[id];
}