import { Event } from "./types";

// Mock data untuk development fallback
export const mockEvents: Event[] = [
  {
    id: "mock-001",
    name: "Workshop Public Speaking 2024",
    date: "2024-09-15",
    endDate: "2024-09-16",
    location: "Hotel X, Jakarta",
    theme: "Speak with Confidence",
    status: "completed",
    maxParticipants: 50,
    description: "Workshop intensif public speaking selama 2 hari dengan 47 peserta dari berbagai perusahaan dan instansi.",
    organizer: "Sarah - Event Manager",
    published: true,
    shortDescription: "Workshop intensif 2 hari tentang teknik public speaking.",
    coverGradient: "from-orange-400 to-orange-600",
    highlights: ["47 Peserta", "CSAT 4.6", "Peningkatan +19 poin"],
    price: 1500000,
    earlyBirdPrice: 1200000,
    earlyBirdDeadline: "2024-08-31",
    paymentMethods: ["Transfer Bank", "OVO", "GoPay"],
    eventType: "public",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    // Extra UI properties
    participants: 47,
    budget: 40000000,
    spent: 17000000,
    csat: 4.6,
    progress: 100,
    checklistDone: 17,
    checklistTotal: 17,
    preTestAvg: 62,
    postTestAvg: 81,
  },
  {
    id: "mock-002",
    name: "Kelas Coaching Batch 5",
    date: "2024-10-01",
    endDate: "2024-10-05",
    location: "Sanrays Office",
    theme: "Leadership Mastery",
    status: "active",
    maxParticipants: 40,
    description: "Program coaching leadership selama 5 hari untuk team leaders dan middle management.",
    organizer: "Sarah - Event Manager",
    published: true,
    shortDescription: "Program coaching leadership 5 hari untuk team leaders.",
    coverGradient: "from-blue-400 to-blue-600",
    highlights: ["32 Peserta", "5 Hari", "Leadership Focus"],
    price: 3500000,
    earlyBirdPrice: 2800000,
    earlyBirdDeadline: "2024-09-15",
    paymentMethods: ["Transfer Bank", "Kartu Kredit"],
    eventType: "public",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    // Extra UI properties
    participants: 32,
    budget: 25000000,
    spent: 12000000,
    csat: 4.3,
    progress: 65,
    checklistDone: 10,
    checklistTotal: 16,
    preTestAvg: 58,
    postTestAvg: 75,
  },
  {
    id: "mock-003",
    name: "Team Building Q4 2024",
    date: "2024-11-15",
    endDate: "2024-11-17",
    location: "Villa Bintang, Puncak",
    theme: "Build Stronger Team",
    status: "preparation",
    maxParticipants: 30,
    description: "Team building 3 hari 2 malam di villa untuk mempererat kebersamaan tim.",
    organizer: "Sarah - Event Manager",
    published: true,
    shortDescription: "Team building 3 hari 2 malam di villa Puncak.",
    coverGradient: "from-emerald-400 to-emerald-600",
    highlights: ["25 Peserta", "3 Hari 2 Malam", "Outdoor Activities"],
    price: 0,
    paymentMethods: [],
    eventType: "internal",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    // Extra UI properties
    participants: 25,
    budget: 35000000,
    spent: 5000000,
    csat: 0,
    progress: 40,
    checklistDone: 6,
    checklistTotal: 15,
    preTestAvg: 0,
    postTestAvg: 0,
  },
];

export function getMockPublishedEvents() {
  return mockEvents.filter(e => e.published);
}

export function getMockEvent(id: string) {
  return mockEvents.find(e => e.id === id);
}
